# Generated by Django 3.1.3 on 2021-07-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210723_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='choices',
            new_name='answers',
        ),
    ]
