# Generated by Django 3.1.3 on 2021-07-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20210725_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='answers',
            new_name='choices',
        ),
    ]
